# .github/workflows/ci.yml

name: CI Workflow (earthly)

on:
  push:
    branches:
    - ci/earthly

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Install asdf
      uses: asdf-vm/actions/setup@v3.0.2

    - name: Install asdf plugins & packages
      run: |
        asdf plugin add earthly https://github.com/YR-ZR0/asdf-earthly
        asdf plugin update --all
        asdf install

    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true

    - name: Earthly version
      run: earthly --version

    - name: Run build
      run: make ci
